dist: trusty
language: cpp
compiler:
# - g++-6
 - clang
sudo: false
os:
 - linux
branches:
  only:
    - develop
notifications:
  email:
    recipients:
      - nialldouglas14@gmail.com

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
#    - george-edison55-precise-backports
#    - george-edison55-cmake-3.x
#    - llvm-toolchain-precise
    packages:
    - g++-6
#    - clang-3.9
    - python3
    - cmake
    - cmake-data
    - doxygen

env:
 - __="Unit tests"
 - __="Code bloat tests"
 - __="cmake tests" NAME=TravisLinuxWorker
 - __="Documentation" NAME=TravisDocumentation
 
#cache:
#  apt: true
#  directories:
#    - llvm-3.9.1
    
before_install:
# -
#    LLVM_VERSION=3.9.1;
#    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
#      if [ -z "$(ls -A llvm-$LLVM_VERSION)" ]; then
#        wget -O llvm-$LLVM_VERSION.tar.xz http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-debian8.tar.xz;
#        mkdir llvm-$LLVM_VERSION;
#        xzcat llvm-$LLVM_VERSION.tar.xz | tar -xvf - --strip 1 -C llvm-$LLVM_VERSION;
#        cd llvm-$LLVM_VERSION/bin;
#        ln -s clang-3.9 clang++-3.9;
#        cd ../..;
#      fi;
#      llvm-$LLVM_VERSION/bin/llvm-config --version;
#      export LLVM_CONFIG="llvm-$LLVM_VERSION/bin/llvm-config";
#      export PATH="$PWD/llvm-$LLVM_VERSION/bin:$PATH";
#    fi
 - if [ "$CXX" = "g++" ]; then export CXX=g++-6; fi

script:
 -
   if [ "$__" = "Unit tests" ]; then
     cd test;
     BUILD_EXTRA=1 ./withgcc.sh || true;
     ./unittests_1 || exit 1;
     ./unittests_coverage || exit 1;
   fi
 -
   if [ "$__" = "Code bloat tests" ]; then
     cd test/constexprs;
     ./with_clang_gcc.sh;
     cat results.xml;
     if grep -q "failure message" results.xml; then
       exit 1;
     fi;
   fi
 -
   if [ "$__" = "cmake tests" ]; then
     ctest -S .ci.cmake -V;
   fi
 -
   if [ "$__" = "Documentation" ]; then
     git config --global push.default simple;
     git config --global user.name "Jenkins nedprod CI";
     git config --global user.email "foo@nowhere";
     cd doc/html;
     git checkout gh-pages;
     cd ../..;
     ctest -S .docs.cmake -V;
     cd doc/html;
     git add . || true;
     git commit -a -m "Travis CI updates documentation" || true;
     git push -f https://jenkins-nedprod:$JENKINS_NEDPROD_PASSWORD@github.com/ned14/boost.outcome gh-pages;
     cd ../..;
   fi
 
after_success:
 - bash -x ./update_coveralls.sh `pwd`

after_failure:
