language: cpp
sudo: false
os:
 - linux
notifications:
  email:
#    recipients:
#      - one@example.com
#      - other@example.com
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - g++-4.9
    - g++-5
    - clang-3.7

before_install:
 - git submodule update --init --recursive

script:
 - cd test
 - BUILD_EXTRA=1 CXX=g++-5 ./withgcc.sh
 - ./unittests_1
 - ./unittests_N
 - ./unittests_coverage
 
after_success:
 - ./update_coveralls.sh

after_failure:
