# version format
version: 0.01.{build}-{branch}
 
# branches to build
branches:
  # blacklist
  except:
    - gh-pages
skip_tags: true
 
# Operating system (build VM template)
os: Visual Studio 2015
init:
  - git config --global core.longpaths true

clone_folder: c:\boost.outcome
platform: x64 
configuration: Release

before_build:
  - git checkout master
  - git submodule update --init --recursive
  - mkdir build
build_script:
  - cd build
  - cmake ..
  - cmake --build . --config Release
after_build:

before_test:
test_script:
  - ctest -D Continuous -C Release
  - bin\Release\unittests-outcome_hl.exe --reporter junit --out results_1.xml
after_test:

on_success:
on_failure:
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results_1.xml))
