# version format
version: 0.01.{build}-{branch}
 
# branches to build
branches:
  # blacklist
  except:
    - gh-pages
skip_tags: true
 
# Operating system (build VM template)
os: Visual Studio 2015
init:
  - git config --global core.longpaths true

clone_folder: c:\boost.outcome
platform: x64 
configuration: Release

before_build:
  - git checkout master
  - git submodule update --init --recursive
build_script:
  - ctest -S .ci.cmake -V
after_build:

before_test:
  - cd cmake_ci
test_script:
  - bin\Release\outcome_hl-unittests.exe --reporter junit --out results.junit.xml
after_test:
  - ..\include\boost\outcome\boost-lite\scripts\merge_junit_results.py results.xml results.junit.xml

on_success:
on_failure:
on_finish:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results.xml))
